name: dev

windows:
  - name: dev
    flex_direction: column
    panes:
      - flex: 55
        flex_direction: row
        panes:
          - name: nvim
            flex: 70
            focus: true
            commands:
              - command: nvim
          - name: terminal
            flex: 30
      - flex: 45
        flex_direction: row
        panes:
          - name: claude-code1
            flex: 1
            commands:
              - command: claude
          - name: claude-code2
            flex: 1
            commands:
              - command: claude
          - name: claude-qa
            flex: 1
            commands:
              - command: claude
