---@type LazySpec
return {
  {
    "nvim-treesitter/nvim-treesitter",
    enable = true,
    event = { "VeryLazy" },
    build = ":TSUpdate",
    main = "nvim-treesitter.configs",
    dependencies = {
      "nvim-treesitter/nvim-tree-docs",
    },
    opts = {
      auto_install = false,
      ensure_installed = {
        "awk",
        "bash",
        "c",
        "c_sharp",
        "clojure",
        "cpp",
        "css",
        "csv",
        "diff",
        "dockerfile",
        "editorconfig",
        "git_config",
        "git_rebase",
        "gitattributes",
        "gitcommit",
        "gitignore",
        "go",
        "gomod",
        "gosum",
        "gpg",
        "graphql",
        "groovy",
        "haskell",
        "java",
        "javadoc",
        "javascript",
        "jq",
        "jsdoc",
        "kotlin",
        "lua",
        "luadoc",
        "make",
        "markdown",
        "mermaid",
        "python",
        "regex",
        "robots",
        "ruby",
        "rust",
        "scss",
        "sql",
        "ssh_config",
        "terraform",
        "tmux",
        "toml",
        "tsv",
        "tsx",
        "typescript",
        "vim",
        "vimdoc",
        "vue",
        "xml",
        "yaml",
      },
      highlight = { enable = true },
      indent = { enable = true },
      tree_docs = { enable = true, },
      incremental_selection = {
        enable = true,
        keymaps = {
          init_selection = "<M-j>",
          node_incremental = "<M-j>",
          scope_incremental = false,
          node_decremental = "<M-k>",
        },
      },
    },
  },
  {
    "windwp/nvim-ts-autotag",
    enable = true,
    event = { "VeryLazy" },
    opts = {},
  },
}
