name: dev-env container image CI

on:
  push:
    branches:
      - master
    paths:
      - .npmrc
      - dev-env-base.dockerfile
      - dev-env.dockerfile
      - coc-package.json
      - fishfile
      - init.vim
      - package.json
  pull_request:
    branches:
      - master
    paths:
      - .npmrc
      - dev-env-base.dockerfile
      - dev-env.dockerfile
      - coc-package.json
      - fishfile
      - init.vim
      - package.json
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (latest, nightly, none)'
        required: true
        default: none
      push:
        description: 'If exectute docker push with build'
        required: true
        default: "false"

jobs:
  build:
    name: Build dev-env container image
    runs-on: ubuntu-latest
    steps:
      - name: Detect parameter
        id: detect-parameter
        run: |
          echo "Trigger on ${{ github.event_name }}"
          if   [ ${{ github.event_name }} = "push" ]; then
            echo "::set-output name=version::latest"
            echo "::set-output name=push::true"
          elif [ ${{ github.event_name }} = "pull_request" ]; then
            echo "::set-output name=version::none"
            echo "::set-output name=push::false"
          else [ ${{ github.event_name }} = "workflow_dispatch" ];
            echo "::set-output name=version::${{ github.event.inputs.version }}"
            echo "::set-output name=push::${{ github.event.inputs.push }}"
          fi
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push dev-env-base
        uses: docker/build-push-action@v2
        with:
          file: dev-env-base.dockerfile
          push: ${{ steps.detect-parameter.outputs.push }}
          tags: ghcr.io/miya10kei/dev-env-base:${{ steps.detect-parameter.outputs.version }}
          cache-from: type=local,src=/tmp/.buildx-cache/dev-env-base
          cache-to: type=local,dest=/tmp/.buildx-cache-new/dev-env-base
      - name: Move dev-env-base cache
        run: |
          rm -rf /tmp/.buildx-cache/dev-env-base
          mv /tmp/.buildx-cache-new/dev-env-base /tmp/.buildx-cache/dev-env-base
      - name: Build and push dev-env
        uses: docker/build-push-action@v2
        with:
          build-args: |
            UID=${{ secrets.UID }}
            LOGIN=${{ secrets.LOGIN }}
            GID=${{ secrets.GID }}
            GROUP=${{ secrets.GROUP }}
            DOCKER_GID=${{ secrets.DOCKER_GID }}
            TAG=${{ steps.detect-parameter.outputs.version }}
          file: dev-env.dockerfile
          push: ${{ steps.detect-parameter.outputs.push }}
          tags: ghcr.io/miya10kei/dev-env:${{ steps.detect-parameter.outputs.version }}
          cache-from: type=local,src=/tmp/.buildx-cache/dev-env
          cache-to: type=local,dest=/tmp/.buildx-cache-new/dev-env
      - name: Move dev-env cache
        run: |
          rm -rf /tmp/.buildx-cache/dev-env
          mv /tmp/.buildx-cache-new/dev-env /tmp/.buildx-cache/dev-env
      - name: Notify result to Slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
