name: dev-env container image CI

on:
  push:
    branches:
      - master
    paths:
      - ./docker/dev-env.dockerfile
      - ./docker/entrypoint.sh
  workflow_dispatch:
    inputs:
      tags:
        description: 'Tag name'
        required: true
        default: miya10kei/nightly
      push:
        description: 'If exectute docker push with build'
        required: true
        default: "false"

jobs:
  build:
    name: Build dev-env container image
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: ./docker/dev-env.dockerfile
          push: false
          tags: miya10kei/dev-env:latest
      - name: Print image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      - name: Notify result to Slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
